version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    container_name: portfolio-backend

  frontend:
    build: ./portfolio
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: portfolio-frontend
